=== k2r/StreamSim/WebContent/models/streamDocType.dtd
<!ELEMENT stream (name, type, attributes+)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ATTLIST type type (relational) "relational">
<!ELEMENT attributes (attribute+)>
<!ELEMENT attribute (value+)>
<!ATTLIST attribute type (integer|text|enumerate) "enumerate">
<!ATTLIST attribute name NMTOKEN "attribute">
<!ELEMENT value (#PCDATA)>
<!ATTLIST value type (min|max|pattern|option) "option">
<!ATTLIST value length CDATA "0">

=== k2r/StreamSim/WebContent/models/opinionModel.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE stream SYSTEM "streamDocType.dtd">
<stream>
	<name>opinion</name>
	<type>relational</type>
	<attributes>
		<attribute type="enumerate" name="name">
			<value type="option">Josiane</value>
			<value type="option">Monique</value>
			<value type="option">Veronique</value>
			<value type="option">Ghislaine</value>
			<value type="option">Viviane</value>
			<value type="option">Virginie</value>
			<value type="option">Therese</value>
			<value type="option">Marie-Solange</value>
			<value type="option">Nadege</value>
		</attribute>
		<attribute type="integer" name="age">
			<value type="min">16</value>
			<value type="max">76</value>
		</attribute>
		<attribute type="enumerate" name="city">
			<value type="option">NY</value>
			<value type="option">TKY</value>
			<value type="option">PAR</value>
			<value type="option">BER</value>
			<value type="option">MAD</value>
			<value type="option">TAC</value>
			<value type="option">LIS</value>
			<value type="option">ROM</value>
			<value type="option">BRA</value>
			<value type="option">SYD</value>
		</attribute>
		<attribute type="enumerate" name="opinion">
			<value type="option">very negative</value>
			<value type="option">negative</value>
			<value type="option">neutral</value>
			<value type="option">positive</value>
			<value type="option">very positive</value>
		</attribute>
	</attributes>
</stream>

=== k2r/StreamSim/models/radarModel.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE stream SYSTEM "streamDocType.dtd">
<stream>
	<name>radar</name>
	<type>relational</type>
	<attributes>
		<attribute type="text" name="registration">
			<value type="pattern" length="1">[0-9]</value>
			<value type="pattern" length="3">[A-Z]</value>
			<value type="pattern" length="2">[0-9]</value>
			<value type="pattern" length="2">[A-Z]</value>
		</attribute>
		<attribute type="integer" name="speed">
			<value type="min">10</value>
			<value type="max">90</value>
		</attribute>
		<attribute type="enumerate" name="make">
			<value type="option">GM</value>
			<value type="option">TOYOTA</value>
			<value type="option">NISSAN</value>
			<value type="option">MITSUBISHI</value>
			<value type="option">FORD</value>
			<value type="option">VOLKSWAGEN</value>
		</attribute>
		<attribute type="enumerate" name="color">
			<value type="option">BLUE</value>
			<value type="option">RED</value>
			<value type="option">WHITE</value>
			<value type="option">SILVER</value>
			<value type="option">BLACK</value>
			<value type="option">YELLOW</value>
		</attribute>
		<attribute type="enumerate" name="location">
			<value type="option">NORTH</value>
			<value type="option">EAST</value>
			<value type="option">WEST</value>
			<value type="option">SOUTH</value>
		</attribute>
	</attributes>
</stream>

=== k2r/StreamSim/models/studentModel.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE stream SYSTEM "streamDocType.dtd">
<stream>
	<name>student</name>
	<type>relational</type>
	<attributes>
		<attribute type="text" name="identifiant">
			<value type="pattern" length="12">[A-9]</value>
		</attribute>
		<attribute type="enumerate" name="prenom">
			<value type="option">Josiane</value>
			<value type="option">Monique</value>
			<value type="option">Veronique</value>
			<value type="option">Ghislaine</value>
			<value type="option">Viviane</value>
			<value type="option">Virginie</value>
			<value type="option">Therese</value>
			<value type="option">Chantal</value>
			<value type="option">Marie-Solange</value>
			<value type="option">Nadege</value>
		</attribute>
		<attribute type="enumerate" name="nom">
			<value type="option">Chambon</value>
			<value type="option">Berenger</value>
			<value type="option">Bernard</value>
			<value type="option">Shapiro</value>
			<value type="option">Pignon</value>
		</attribute>
		<attribute type="integer" name="age">
			<value type="min">18</value>
			<value type="max">25</value>
		</attribute>
		<attribute type="enumerate" name="dept">
			<value type="option">INFO</value>
			<value type="option">MECA</value>
			<value type="option">BIO</value>
		</attribute>
		<attribute type="enumerate" name="promotion">
			<value type="option">L1</value>
			<value type="option">L2</value>
			<value type="option">L3</value>
			<value type="option">M1</value>
			<value type="option">M2</value>
		</attribute>
		<attribute type="enumerate" name="parcours">
			<value type="option">professionel</value>
			<value type="option">recherche</value>
			<value type="option">alternant</value>
		</attribute>
	</attributes>
</stream>
