=== k2r/StreamSim/WebContent/variations/models/variationDocType.dtd
<!ELEMENT variations ((profile+, transition*)+)>
<!ELEMENT profile (duration)>
<!ELEMENT transition (duration)>
<!ATTLIST profile type (standard|zipf) "standard">
<!ATTLIST profile rate CDATA "0">
<!ATTLIST profile skew CDATA #IMPLIED>
<!ATTLIST transition type (linear|exponential|logarithmic) "linear">
<!ELEMENT duration (#PCDATA)>

=== k2r/StreamSim/variations/models/testStdVar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE variations SYSTEM "variationDocType.dtd" >
<variations>
  <profile type="standard" rate="30">
    <duration>150</duration>
  </profile>
  <transition type="exponential">
  	<duration>250</duration>
  </transition>
  <profile type="standard" rate="350">
    <duration>400</duration>
  </profile>
  <transition type="exponential">
  	<duration>50</duration>
  </transition>
  <profile type="standard" rate="30">
    <duration>350</duration>
  </profile>
</variations>

=== k2r/StreamSim/WebContent/variations/models/testZipf15Var.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE variations SYSTEM "variationDocType.dtd" >
<variations>
  <profile type="zipf" skew="1.5" rate="5">
    <duration>60</duration>
  </profile>
  <transition type="exponential">
  	<duration>240</duration>
  </transition>
  <profile type="zipf" skew="1.5" rate="250">
    <duration>330</duration>
  </profile>
  <transition type="exponential">
  	<duration>240</duration>
  </transition>
  <profile type="zipf" skew="1.5" rate="5">
    <duration>60</duration>
  </profile>
  <transition type="linear">
  	<duration>0</duration>
  </transition>
  <profile type="zipf" skew="1.5" rate="100">
    <duration>10</duration>
  </profile>
  <transition type="linear">
  	<duration>0</duration>
  </transition>
  <profile type="zipf" skew="1.5" rate="5">
  	<duration>60</duration>
  </profile>
</variations>

=== k2r/StreamSim/WebContent/variations/models/scaleIncreaseVar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE stream SYSTEM "variationDocType.dtd">
<variations>
	<profile type="standard" rate="30">
		<duration>150</duration>
	</profile>
	<transition type="linear">
		<duration>0</duration>
	</transition>
	<profile type="standard" rate="75">
		<duration>150</duration>
	</profile>
	<transition type="linear">
		<duration>0</duration>
	</transition>
	<profile type="standard" rate="200">
		<duration>150</duration>
	</profile>
	<transition type="linear">
		<duration>0</duration>
	</transition>
	<profile type="standard" rate="350">
		<duration>450</duration>
	</profile>
	<transition type="linear">
		<duration>0</duration>
	</transition>
	<profile type="standard" rate="200">
		<duration>200</duration>
	</profile>
	<transition type="linear">
		<duration>0</duration>
	</transition>
	<profile type="standard" rate="30">
		<duration>250</duration>
	</profile>
<!--  	<transition type="linear">
		<duration>0</duration>
	</transition>
	<profile type="standard" rate="30">
		<duration></duration>
	</profile>
	<transition type="linear">
		<duration>0</duration>
	</transition>
	<profile type="standard" rate="800">
		<duration>60</duration>
	</profile>
	<transition type="linear">
		<duration>0</duration>
	</transition>
	<profile type="standard" rate="900">
		<duration>60</duration>
	</profile>
	<transition type="linear">
		<duration>0</duration>
	</transition>
	<profile type="standard" rate="1000">
		<duration>60</duration>
	</profile>-->
</variations>
